import Head from 'next/head'
export type PropsType={

    info:string
}


export default function About(props:PropsType) {
    return (
        <div>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name={"viewport"}/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>About</h1>
                <p>{props.info}</p>
            </main>
        </div>
    )
}
export async function getStaticProps(){
    console.log('只在build构筑时执行')
    return{
        props:{
            info:'我是从服务端获取的数据'
        }
    }
}